import { CustomRule } from '../models/types';

export const DEFAULT_RULES: CustomRule[] = [
  {
    id: 'rule-sql-injection',
    title: 'Ban Raw SQL String Concatenation & Injections',
    category: 'SECURITY',
    severity: 'CRITICAL',
    description: 'Prohibit concatenating dynamic variables, strings, or template literals into SQL queries. Enforce parameterized queries or ORMs.',
    pattern: '(SELECT|INSERT|UPDATE|DELETE).*[\\+\\$]\\{?|rawQuery\\(.*\\+|AND\\s+\\w+\\s*=\\s*\'',
    suggestedCodeTemplate: 'const query = "SELECT * FROM table WHERE id = ?";\nreturn await this.db.query(query, [id]);',
    enabled: true,
    isDefault: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'rule-hardcoded-secrets',
    title: 'Disallow Hardcoded API Keys, Passwords & Tokens',
    category: 'SECURITY',
    severity: 'CRITICAL',
    description: 'Disallow hardcoded tokens, passwords, and private keys in source code. Enforce reading credentials from environment variables (process.env) or Key Vaults.',
    pattern: '(apiKey|secret|password|bearer|token)\\s*=\\s*["\'][a-zA-Z0-9_\\-]{8,}["\']',
    suggestedCodeTemplate: 'const apiKey = process.env.SERVICE_API_KEY;\nif (!apiKey) throw new ConfigurationError("Missing SERVICE_API_KEY");',
    enabled: true,
    isDefault: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'rule-srp-god-class',
    title: 'Enforce Single Responsibility Principle (SRP)',
    category: 'SOLID',
    severity: 'CRITICAL',
    description: 'Reject "God classes" or service layers that combine unrelated concerns (e.g., database queries, email dispatching, payment parsing, and UI formatting all in one class).',
    pattern: '(class\\s+\\w+Service|class\\s+\\w+Manager).*(sendEmail|sendNotification|executeSql|processStripePayment)',
    suggestedCodeTemplate: '// Extract distinct concerns into isolated domain services:\n// 1. UserRepository (Data Access)\n// 2. NotificationDispatcher (Communication)\n// 3. UserRegistrationUseCase (Orchestrator)',
    enabled: true,
    isDefault: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'rule-dip-direct-instantiation',
    title: 'Enforce Dependency Inversion (DIP) over "new Service()"',
    category: 'SOLID',
    severity: 'WARNING',
    description: 'High-level business modules should depend on abstractions (interfaces), not direct concretions or instantiating clients with `new Client()` inside constructors.',
    pattern: 'new\\s+(EmailService|DatabaseConnection|StripeClient|RedisClient)\\(',
    suggestedCodeTemplate: 'constructor(private readonly emailService: INotificationService) {}',
    enabled: true,
    isDefault: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'rule-n-plus-one-query',
    title: 'Flag N+1 Query Loops & Synchronous I/O in Iterations',
    category: 'PERFORMANCE',
    severity: 'CRITICAL',
    description: 'Prevent executing database queries or asynchronous HTTP requests inside loops (`forEach`, `for...of`, `map`). Enforce batch queries (`WHERE IN (?)`) or DataLoader pattern.',
    pattern: '(for\\s*\\(.*\\)|\\.map\\(|\\.forEach\\().*(await\\s+.*\\.query|await\\s+.*\\.find|await\\s+fetch)',
    suggestedCodeTemplate: 'const userIds = orders.map(o => o.userId);\nconst users = await this.userRepository.findByIds(userIds);',
    enabled: true,
    isDefault: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'rule-unhandled-promise-rejection',
    title: 'Prohibit Unhandled Async Errors & Floating Promises',
    category: 'BUG',
    severity: 'WARNING',
    description: 'Catch and handle async operations or explicitly return promises. Floating promises cause unhandled rejections and hidden service crashes.',
    pattern: 'async\\s+.*\\{([^}]*(?<!try\\s*\\{[^}]*))await\\s+',
    suggestedCodeTemplate: 'try {\n  await this.paymentService.charge(order);\n} catch (error) {\n  this.logger.error("Payment failed", error);\n  throw new PaymentProcessingException(error.message);\n}',
    enabled: true,
    isDefault: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'rule-no-console-log-prod',
    title: 'Ban Debug console.log in Production Code',
    category: 'CLEAN_CODE',
    severity: 'SUGGESTION',
    description: 'Debug `console.log` statements degrade performance in high-throughput node servers and pollute stdout. Enforce structured logger (Pino/Winston).',
    pattern: 'console\\.(log|debug|info)\\(',
    suggestedCodeTemplate: 'this.logger.debug("Processing user transition", { userId });',
    enabled: true,
    isDefault: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'rule-lsp-type-casting-override',
    title: 'Enforce Liskov Substitution Principle (LSP)',
    category: 'SOLID',
    severity: 'WARNING',
    description: 'Derived classes must be substitutable for their base types without throwing unexpected UnsupportedOperationErrors or mutating return shapes.',
    pattern: 'throw\\s+new\\s+(Error|NotImplementedException|UnsupportedOperationException)\\([\'"]Not implemented|Not supported',
    suggestedCodeTemplate: '// Segregate interface into finer capabilities so classes only implement relevant contracts.',
    enabled: true,
    isDefault: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
];
